// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: sdk.proto

package tools_sdk_nsdk_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadTLSResourcesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DownloadTLSResourcesRequest) Reset() {
	*x = DownloadTLSResourcesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadTLSResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTLSResourcesRequest) ProtoMessage() {}

func (x *DownloadTLSResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTLSResourcesRequest.ProtoReflect.Descriptor instead.
func (*DownloadTLSResourcesRequest) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{0}
}

type DownloadTLSResourcesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Returns TLS public key in DER format
	PublicKey []byte `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	// Returns TLS certificate in DER format
	Certificate []byte `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *DownloadTLSResourcesResponse) Reset() {
	*x = DownloadTLSResourcesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadTLSResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTLSResourcesResponse) ProtoMessage() {}

func (x *DownloadTLSResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTLSResourcesResponse.ProtoReflect.Descriptor instead.
func (*DownloadTLSResourcesResponse) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadTLSResourcesResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DownloadTLSResourcesResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{3}
}

type RegisterPublicKeyAsUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Namespace where to search for user
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// User login
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// User password (password attached to user identity)
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Users public key in DER format
	PublicKey []byte `protobuf:"bytes,4,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *RegisterPublicKeyAsUserRequest) Reset() {
	*x = RegisterPublicKeyAsUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPublicKeyAsUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPublicKeyAsUserRequest) ProtoMessage() {}

func (x *RegisterPublicKeyAsUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPublicKeyAsUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterPublicKeyAsUserRequest) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterPublicKeyAsUserRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterPublicKeyAsUserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RegisterPublicKeyAsUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterPublicKeyAsUserRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type RegisterPublicKeyAsUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// X509 certificate in DER format
	Certificate []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *RegisterPublicKeyAsUserResponse) Reset() {
	*x = RegisterPublicKeyAsUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPublicKeyAsUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPublicKeyAsUserResponse) ProtoMessage() {}

func (x *RegisterPublicKeyAsUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPublicKeyAsUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterPublicKeyAsUserResponse) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterPublicKeyAsUserResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

var File_sdk_proto protoreflect.FileDescriptor

var file_sdk_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x6f, 0x6f,
	0x6c, 0x73, 0x5f, 0x73, 0x64, 0x6b, 0x5f, 0x73, 0x64, 0x6b, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x4c, 0x53, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x1c, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x4c, 0x53, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x1e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x41, 0x73,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x43, 0x0a, 0x1f, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x41, 0x73, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x32, 0xb8, 0x02, 0x0a,
	0x0a, 0x53, 0x44, 0x4b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x14, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x4c, 0x53, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x2a, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x73, 0x64, 0x6b, 0x5f,
	0x73, 0x64, 0x6b, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x4c, 0x53, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x73, 0x64, 0x6b, 0x5f, 0x73, 0x64, 0x6b, 0x2e,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x4c, 0x53, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x04,
	0x50, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x73, 0x64, 0x6b,
	0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x73, 0x64, 0x6b, 0x5f, 0x73, 0x64, 0x6b,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a,
	0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x41, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2d, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x73,
	0x5f, 0x73, 0x64, 0x6b, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x41, 0x73, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f,
	0x73, 0x64, 0x6b, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x41, 0x73, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x73, 0x6c, 0x61, 0x6d, 0x79,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x42, 0x50, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x73, 0x64,
	0x6b, 0x2f, 0x73, 0x64, 0x6b, 0x3b, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x73, 0x64, 0x6b, 0x5f,
	0x6e, 0x73, 0x64, 0x6b, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sdk_proto_rawDescOnce sync.Once
	file_sdk_proto_rawDescData = file_sdk_proto_rawDesc
)

func file_sdk_proto_rawDescGZIP() []byte {
	file_sdk_proto_rawDescOnce.Do(func() {
		file_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdk_proto_rawDescData)
	})
	return file_sdk_proto_rawDescData
}

var file_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sdk_proto_goTypes = []interface{}{
	(*DownloadTLSResourcesRequest)(nil),     // 0: tools_sdk_sdk.DownloadTLSResourcesRequest
	(*DownloadTLSResourcesResponse)(nil),    // 1: tools_sdk_sdk.DownloadTLSResourcesResponse
	(*PingRequest)(nil),                     // 2: tools_sdk_sdk.PingRequest
	(*PingResponse)(nil),                    // 3: tools_sdk_sdk.PingResponse
	(*RegisterPublicKeyAsUserRequest)(nil),  // 4: tools_sdk_sdk.RegisterPublicKeyAsUserRequest
	(*RegisterPublicKeyAsUserResponse)(nil), // 5: tools_sdk_sdk.RegisterPublicKeyAsUserResponse
}
var file_sdk_proto_depIdxs = []int32{
	0, // 0: tools_sdk_sdk.SDKService.DownloadTLSResources:input_type -> tools_sdk_sdk.DownloadTLSResourcesRequest
	2, // 1: tools_sdk_sdk.SDKService.Ping:input_type -> tools_sdk_sdk.PingRequest
	4, // 2: tools_sdk_sdk.SDKService.RegisterPublicKeyAsUser:input_type -> tools_sdk_sdk.RegisterPublicKeyAsUserRequest
	1, // 3: tools_sdk_sdk.SDKService.DownloadTLSResources:output_type -> tools_sdk_sdk.DownloadTLSResourcesResponse
	3, // 4: tools_sdk_sdk.SDKService.Ping:output_type -> tools_sdk_sdk.PingResponse
	5, // 5: tools_sdk_sdk.SDKService.RegisterPublicKeyAsUser:output_type -> tools_sdk_sdk.RegisterPublicKeyAsUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_proto_init() }
func file_sdk_proto_init() {
	if File_sdk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadTLSResourcesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadTLSResourcesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPublicKeyAsUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPublicKeyAsUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_proto_goTypes,
		DependencyIndexes: file_sdk_proto_depIdxs,
		MessageInfos:      file_sdk_proto_msgTypes,
	}.Build()
	File_sdk_proto = out.File
	file_sdk_proto_rawDesc = nil
	file_sdk_proto_goTypes = nil
	file_sdk_proto_depIdxs = nil
}
