version: "3.4"
  # SYSTEM



  # NATIVE

  #native_catalog:
  #  container_name: native_catalog
  #  build:
  #    context: .
  #    dockerfile: catalog/Dockerfile
  #  ports:
  #  - 1234:1234
  #  environment:
  #    DB_URL: mongodb://root:example@system_db/admin
  #    DB_NAME: admin
  #    NATIVE_CACHE_REDIS_CONNECTION_URL: redis://system_cache
  #    NATIVE_CACHE_REDIS_CONNECTION_TIMEOUT: 5000
  #    OTEL_EXPORTER_OTLP_ENDPOINT: "http://system_jaeger:55680"
  #    OTEL_SERVICE_NAME: "native_catalog"
  #  depends_on:
  #    - system_cache
  #    - system_jaeger
  #    - system_db