site_name: Open Business Platform
site_description: 'An open-source set of services and tools that makes it easy to build, release, and operate production-ready Industry 4.0+ business solutions.'
site_url: 'https://openbp.io/'
repo_name: 'slamy-solutions/openbp'
repo_url: 'https://github.com/slamy-solutions/openbp'
edit_uri: 'edit/mainline/site/content'
copyright: 'Copyright &copy; 2022 Slamy Solutions'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
extra:
#  analytics:
#    provider: google
#    property: G-7S4JR3KFHK
  alternate:
    - name: English
      link: ./en/
      lang: en

nav:
  - Home: index.md
  - Documentation:
    - Overview: docs/overview.en.md
    - Getting Started:
      - Deploy for production:
        - Docker-compose: docs/getting-started/prod/compose.en.md
        #- Kubernetes (Helm): docs/getting-started/prod/kubernetes.en.md
        - Raspberry Pi: docs/getting-started/prod/rpi.en.md
      #- Deploy for development: docs/getting-started/dev.en.md
      #- Develop your first module: docs/getting-started/first-app-tutorial.en.md
    - Concepts:
      - IaC: docs/concepts/IaC.en.md
      - GIT CI/CD: docs/concepts/cicd.en.md
      - Use the language you want: docs/concepts/languageYouWant.en.md
    - Modules:
      - What is the module?: docs/modules/overview.en.md
      - System:
        - What is the system module?: docs/modules/system/overview.md
        - DB: docs/modules/system/db.md
        - Vault: docs/modules/system/vault.md
        - NATS: docs/modules/system/nats.md
        - Cache: docs/modules/system/cache.md
        - Redis: docs/modules/system/redis.md
      - Native:
        - What is the native module?: docs/modules/native/overview.en.md
        - Namespace: docs/modules/native/namespace.en.md
        - KeyValueStorage: docs/modules/native/keyvaluestorage.en.md
        - IAM:
          - What is IAM?: docs/modules/native/iam/iam.en.md
          - Policy: docs/modules/native/iam/policy.en.md
          - Identity: docs/modules/native/iam/identity.en.md
          - Token: docs/modules/native/iam/token.en.md
          - Auth: docs/modules/native/iam/auth.en.md
          - Authentication:
            - Password: docs/modules/native/iam/authentication/password.en.md
          - Actor:
            - User: docs/modules/native/iam/actor/user.en.md

  #- Community:
  #    - Get Involved: community/get-involved.en.md
  #    - Guides and Resources: community/guides.en.md

  - License:
    - License information: license/license.en.md
    - FAQ: license/faq.en.md
    - Acknowledgements: license/acknowledgements.en.md

  
theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font:
    text: Red Hat Display
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/images/favicon.png
  language: en
  features:
    - tabs
    - instant
    - navigation.tabs

markdown_extensions:
  - def_list
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - site/overrides/.icons

plugins:
    - search
    - redirects:
        redirect_maps:
          'docs/installing.md': 'docs/getting-started/install.en.md'
          'docs/getting-started.md': 'docs/getting-started/first-app-tutorial.en.md'
    #- i18n:
    #    default_language: en
    #    languages:
    #      en: english
    #    material_alternate: false