site_name: Open Business Platform
site_description: 'All in one IT platform for businness'
site_url: 'https://openbp.io/'
repo_name: 'slamy-solutions/openbp'
repo_url: 'https://github.com/slamy-solutions/openbp'
edit_uri: 'edit/mainline/site/content'
copyright: 'Copyright &copy; 2022 Slamy Solutions'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
extra:
#  analytics:
#    provider: google
#    property: G-7S4JR3KFHK
  alternate:
    - name: English
      link: ./en/
      lang: en

nav:
  - Home: index.en.md
  - Documentation:
    - Overview: docs/overview.en.md
    - Getting Started:
      - Install Copilot: docs/getting-started/install.en.md
      - (Optional) Verify the installation: docs/getting-started/verify.en.md
      - Deploy your first application: docs/getting-started/first-app-tutorial.en.md
    - Modules:
      - What is the module?: docs/modules/overview.en.md
      - System:
        - What is the system module?: docs/modules/system/overview.en.md
        - MongoDB: docs/modules/system/mongodb.en.md
        - Rabbitmq: docs/modules/system/rabbitmq.en.md
        - Redis Cache: docs/modules/system/redis_cache.en.md
        - Redis Big Cache: docs/modules/system/redis_big_cache.en.md
      - Native:
        - What is the native module?: docs/modules/native/overview.en.md
        - Namespace: docs/modules/native/namespace.en.md
        - KeyValueStorage: docs/modules/native/keyvaluestorage.en.md
        - IAM:
          - What is IAM?: docs/modules/native/iam/iam.en.md
          - OAuth: docs/modules/native/iam/oauth.en.md

  - Community:
      - Get Involved: community/get-involved.en.md
      - Guides and Resources: community/guides.en.md
theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font: false
  icon:
    logo: octicons/terminal-16
  favicon: assets/images/cli.png
  language: en
  features:
    - tabs
    - instant
    - navigation.tabs

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - site/overrides/.icons

plugins:
    - search
    - redirects:
        redirect_maps:
            'docs/installing.md': 'docs/getting-started/install.en.md'
            'docs/getting-started.md': 'docs/getting-started/first-app-tutorial.en.md'
    #- i18n:
    #    default_language: en
    #    languages:
    #      en: english
    #    material_alternate: false