version: '3.8'

services:
  native_namespace:
    image: openbp/obp-native-namespace:${OPENBP_VERSION:-latest}
    container_name: native_namespace
    restart: always
    depends_on:
      - system_db
      - system_cache
      - system_nats
    networks:
      - internal

  native_keyvaluestorage:
    image: openbp/obp-native-keyvaluestorage:${OPENBP_VERSION:-latest}
    container_name: native_keyvaluestorage
    restart: always
    depends_on:
      - system_db
      - system_cache
      - system_nats
      - native_namespace
    networks:
      - internal

  native_iam:
    image: openbp/obp-native-iam:${OPENBP_VERSION:-latest}
    container_name: native_iam
    restart: always
    depends_on:
      - system_db
      - system_cache
      - system_nats
      - system_vault
      - native_namespace
    networks:
      - internal

  native_actor_user:
    image: openbp/obp-native-actor-user:${OPENBP_VERSION:-latest}
    container_name: native_actor_user
    restart: always
    depends_on:
      - system_db
      - system_cache
      - system_nats
      - native_iam
    networks:
      - internal
