version: "3.4"
services:
  tools_rest:
    container_name: tools_rest
    restart: always
    build:
      context: .
      dockerfile: modules/tools/services/rest/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tools_rest.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.tools_rest.entrypoints=web"

      - "traefik.http.routers.tools_rest_sec.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.tools_rest_sec.entrypoints=websecure"
      - "traefik.http.routers.tools_rest_sec.tls=true"
    environment:
      ALLOW_ROOT_USER_INIT: "true"
      DEFAULT_ROOT_USER_LOGIN: ""
      DEFAULT_ROOT_USER_PASSWORD: ""
    depends_on:
      - native_namespace
      - native_iam
      - native_keyvaluestorage
      - system_telemetry
    ports:
      - "127.0.0.1:28300:8080" # For testing

  tools_gui:
    container_name: tools_gui
    restart: always
    build:
      context: .
      dockerfile: modules/tools/services/gui/Dockerfile
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.tools_gui.rule=PathPrefix(`/`)"
      - "traefik.http.routers.tools_gui.entrypoints=web"

      - "traefik.http.routers.tools_gui_sec.rule=PathPrefix(`/`)"
      - "traefik.http.routers.tools_gui_sec.entrypoints=websecure"
      - "traefik.http.routers.tools_gui_sec.tls=true"
    depends_on:
      - tools_rest
      - system_proxy

  tools_sdk:
    container_name: tools_sdk
    restart: always
    build:
      context: .
      dockerfile: modules/tools/services/sdk/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tools_sdk.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.tools_sdk.loadbalancer.server.port=80"

      - "traefik.http.middlewares.tools_sdk-pass-tls-cert.passtlsclientcert.pem=true"
      - "traefik.http.middlewares.tools_sdk-strip-prefix.stripprefix.prefixes=/sdk"

      - "traefik.http.routers.tools_sdk.rule=PathPrefix(`/sdk`)"
      - "traefik.http.routers.tools_sdk.entrypoints=websecure"
      - "traefik.http.routers.tools_sdk.tls=true"
      - "traefik.http.routers.tools_sdk.service=tools_sdk"
      - "traefik.http.routers.tools_sdk.middlewares=tools_sdk-pass-tls-cert@docker,tools_sdk-strip-prefix@docker"
    depends_on:
      - native_namespace
      - native_iam
      - native_keyvaluestorage
      - system_telemetry
      - system_proxy