apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "native.fullname" . }}-namespace"
  namespace: {{ print .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ include "native.fullname" . }}-namespace"
    {{- include "native.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.namespace.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "native.fullname" . }}-namespace"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "native.fullname" . }}-namespace"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
      - name: namespace
        image: "{{ .Values.namespace.image.repository }}:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        env:
        - name: SYSTEM_DB_URL
          value: "mongodb://root:example@{{ .Release.Name }}-system-mongodb-headless/admin"
        - name: SYSTEM_CACHE_URL
          value: "redis://{{ .Release.Name }}-system-redis-cache-headless"
        - name: SYSTEM_NATS_URL
          value: "nats://{{ .Release.Name }}-system-nats:4222"
        resources:
          limits:
            cpu: 1000m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 20Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "native.fullname" . }}-namespace"
  namespace: {{ print .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ include "native.fullname" . }}-namespace"
    {{- include "native.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "native.fullname" . }}-namespace"
  minReplicas: {{ .Values.namespace.minReplicas }}
  maxReplicas: {{ .Values.namespace.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "native.fullname" . }}-namespace"
  namespace: {{ print .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ include "native.fullname" . }}-namespace"
    {{- include "native.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: "{{ include "native.fullname" . }}-namespace"
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80