version: "3.4"
services:

  system_proxy:
    restart: always
    image: traefik:2.5.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"

  system_cache:
    restart: always
    container_name: system_cache
    build:
      context: modules/system/services/redis-cache
      dockerfile: Dockerfile
    environment:
      MAXMEMORY: 512mb

#  system_bigcache:
#    restart: always
#    container_name: system_bigcache
#    build:
#      context: modules/system/services/redis-bigCache
#      dockerfile: Dockerfile
#    environment:
#      MAXMEMORY: 1024mb

  system_db:
    restart: always
    container_name: system_db
    build:
      context: modules/system/services/mongodb
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  system_telemetry:
    restart: always
    container_name: system_telemetry
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
    - 55680:55680
    - 16686:16686
    - 14269:14269
    - 14268:14268

  system_nats:
    restart: always
    image: nats:latest