version: "3.4"
services:

  system_proxy:
    restart: always
    image: traefik:2.5.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--tracing=true"
      - "--tracing.serviceName=traefik"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.samplingServerURL=http://system_telemetry:5778/sampling"
      - "--tracing.jaeger.localAgentHostPort=system_telemetry:6831"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  system_cache:
    restart: always
    container_name: system_cache
    build:
      context: modules/system/services/redis-cache
      dockerfile: Dockerfile
    environment:
      MAXMEMORY: 512mb

#  system_bigcache:
#    restart: always
#    container_name: system_bigcache
#    build:
#      context: modules/system/services/redis-bigCache
#      dockerfile: Dockerfile
#    environment:
#      MAXMEMORY: 1024mb

  system_db:
    restart: always
    container_name: system_db
    build:
      context: modules/system/services/mongodb
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  system_telemetry:
    restart: always
    container_name: system_telemetry
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "16686:16686"

  system_nats:
    restart: always
    container_name: system_nats
    image: nats:latest
    command: --js --sd /data