apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "system.fullname" . }}-vault"
  namespace: {{ print .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ include "system.fullname" . }}-vault"
    {{- include "system.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "system.fullname" . }}-vault"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "system.fullname" . }}-vault"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
      - name: vault
        image: "{{ .Values.vault.image.repository }}:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 4000m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "system.fullname" . }}-vault"
  namespace: {{ print .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ include "system.fullname" . }}-vault"
    {{- include "system.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: "{{ include "system.fullname" . }}-vault"
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80