name: 'Publish service docker image'
description: 'Builds and publishes docker image to the pre-defined repository. Action created only for publishing services from the OpenBP.'

inputs:
  context:
    description: 'Context of the dockerfile'
    required: false
    default: '.'
  dockerifle:
    description: 'Path to the dockerfile'
    required: true
    default: 'Dockerfile'
  tags:
    description: 'List of tags for the image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ inputs.tags }}
