version: "3.4"
services:
  native_namespace:
    container_name: native_namespace
    build:
      context: modules/native/services/namespace
      dockerfile: Dockerfile
    environment:
      SYSTEM_MONGODB_URL: mongodb://root:example@system_db
      SYSTEM_REDIS_CACHE_CONNECTION_URL: redis://system_cache
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_namespace"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry