version: "3.4"
services:
  native_namespace:
    container_name: native_namespace
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/namespace/Dockerfile
    environment:
      SYSTEM_MONGODB_URL: mongodb://root:example@system_db
      SYSTEM_REDIS_CACHE_CONNECTION_URL: redis://system_cache
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_namespace"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - system_rabbitmq

  native_lambda_manager:
    container_name: native_lambda_manager
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/lambda/manager/Dockerfile
    environment:
      SYSTEM_MONGODB_URL: mongodb://root:example@system_db
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_lambda_manager"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - system_rabbitmq

  native_lambda_entrypoint:
    container_name: native_lambda_entrypoint
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/lambda/entrypoint/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_lambda_entrypoint"
    depends_on:
      - system_telemetry
      - system_rabbitmq
      - native_lambda_manager

  native_keyvaluestorage:
    container_name: native_keyvaluestorage
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/keyvaluestorage/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_keyvaluestorage"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - system_rabbitmq
      - native_namespace
  
  native_iam_config:
    container_name: native_iam_config
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/iam/config/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_iam_config"
    depends_on:
      - system_cache
      - system_telemetry
      - native_keyvaluestorage

  native_iam_policy:
    container_name: native_iam_policy
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/iam/policy/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_iam_policy"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - native_namespace

  native_iam_identity:
    container_name: native_iam_identity
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/iam/identity/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_iam_identity"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - native_namespace
      - native_iam_policy

  native_iam_token:
    container_name: native_iam_token
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/iam/token/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_iam_token"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - native_namespace

  native_iam_authentication_password:
    container_name: native_iam_authentication_password
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/iam/authentication/password/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_iam_authentication_password"
    depends_on:
      - system_db
      - system_telemetry
      - native_namespace

  native_file:
    container_name: native_file
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/file/Dockerfile
    environment:
      SYSTEM_MONGODB_URL: mongodb://root:example@system_db
      SYSTEM_REDIS_CACHE_CONNECTION_URL: redis://system_cache
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_file"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - system_rabbitmq
      - native_namespace