version: "3.4"
services:
  native_namespace:
    container_name: native_namespace
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/namespace/Dockerfile
    environment:
      SYSTEM_MONGODB_URL: mongodb://root:example@system_db
      SYSTEM_REDIS_CACHE_CONNECTION_URL: redis://system_cache
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_namespace"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
    ports:
      - "127.0.0.1:28250:80" # For testing

  native_keyvaluestorage:
    container_name: native_keyvaluestorage
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/keyvaluestorage/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_keyvaluestorage"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - native_namespace
    ports:
      - "127.0.0.1:28251:80" # For testing

  native_iam:
    container_name: native_iam
    restart: always
    build:
      context: .
      dockerfile: modules/native/services/iam/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "native_iam"
    depends_on:
      - system_db
      - system_cache
      - system_telemetry
      - system_vault
      - native_namespace
    ports:
      - "127.0.0.1:28252:80" # For testing