version: "3.4"
services:
  iot_core:
    container_name: erp_core
    restart: always
    build:
      context: .
      dockerfile: modules/erp/services/core/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "system_telemetry:55680"
      OTEL_SERVICE_NAME: "erp_core"
    depends_on:
      - system_telemetry
      - system_nats
      - system_cache
      - system_db
    ports:
      - "127.0.0.1:28310:80" # For testing