name: "Release new version"

on:
  push:
    tags:
      - '*'

jobs:
  setup:
    name: Extract tag name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}

  
  tests:
    name: Test
    uses: ./.github/workflows/test.yml
  
  # System
  publish-system-vault:
    needs: [tests,setup]
    name: Publish system_vault docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/system/services/vault/Dockerfile
      tags: openbp/obp-system-vault:latest,openbp/obp-system-vault:${{ needs.setup.outputs.tag }}
    secrets: inherit

  # Native
  publish-native-namespace:
    needs: [tests,setup]
    name: Publish native_namespace docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/namespace/Dockerfile
      tags: openbp/obp-native-namespace:latest,openbp/obp-native-namespace:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-keyvaluestorage:
    needs: [tests,setup]
    name: Publish native_keyvaluestorage docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/keyvaluestorage/Dockerfile
      tags: openbp/obp-native-keyvaluestorage:latest,openbp/obp-native-keyvaluestorage:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-iam-policy:
    needs: [tests,setup]
    name: Publish native_iam_policy docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/iam/policy/Dockerfile
      tags: openbp/obp-native-iam-policy:latest,openbp/obp-native-iam-policy:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-iam-role:
    needs: [tests,setup]
    name: Publish native_iam_role docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/iam/role/Dockerfile
      tags: openbp/obp-native-iam-role:latest,openbp/obp-native-iam-role:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-iam-token:
    needs: [tests,setup]
    name: Publish native_iam_token docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/iam/token/Dockerfile
      tags: openbp/obp-native-iam-token:latest,openbp/obp-native-iam-token:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-iam-auth:
    needs: [tests,setup]
    name: Publish native_iam_auth docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/iam/auth/Dockerfile
      tags: openbp/obp-native-iam-auth:latest,openbp/obp-native-iam-auth:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-iam-identity:
    needs: [tests,setup]
    name: Publish native_iam_identity docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/iam/identity/Dockerfile
      tags: openbp/obp-native-iam-identity:latest,openbp/obp-native-iam-identity:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-iam-authentication:
    needs: [tests,setup]
    name: Publish native_iam_authentication docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/iam/authentication/Dockerfile
      tags: openbp/obp-native-iam-authentication:latest,openbp/obp-native-iam-authentication:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-actor-user:
    needs: [tests,setup]
    name: Publish native_actor_user docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/actor/user/Dockerfile
      tags: openbp/obp-native-actor-user:latest,openbp/obp-native-actor-user:${{ needs.setup.outputs.tag }}
    secrets: inherit

  # Tools
  publish-tools-rest:
    needs: [tests,setup]
    name: Publish tools_rest docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/tools/services/rest/Dockerfile
      tags: openbp/obp-tools-rest:latest,openbp/obp-tools-rest:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-tools-gui:
    needs: [tests,setup]
    name: Publish tools_gui docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/tools/services/gui/Dockerfile
      tags: openbp/obp-tools-gui:latest,openbp/obp-tools-gui:${{ needs.setup.outputs.tag }}
    secrets: inherit

  github-release:
    needs:
      - publish-native-namespace
      - publish-native-keyvaluestorage
      - publish-native-iam-policy
      - publish-native-iam-role
      - publish-native-iam-token
      - publish-native-iam-auth
      - publish-native-iam-identity
      - publish-native-iam-authentication-password
      - publish-native-actor-user
      - publish-tools-rest
      - publish-tools-gui
    name: Create github release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}