name: "Release new version"

on:
  push:
    tags:
      - '*'

jobs:
  setup:
    name: Extract tag name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}

  
  tests:
    name: Test
    uses: ./.github/workflows/test.yml
  
  # System
  publish-system-vault:
    needs: [tests,setup]
    name: Publish system_vault docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/system/services/vault/Dockerfile
      tags: openbp/obp-system-vault:latest,openbp/obp-system-vault:${{ needs.setup.outputs.tag }}
    secrets: inherit

  # Native
  publish-native-namespace:
    needs: [tests,setup]
    name: Publish native_namespace docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/namespace/Dockerfile
      tags: openbp/obp-native-namespace:latest,openbp/obp-native-namespace:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-keyvaluestorage:
    needs: [tests,setup]
    name: Publish native_keyvaluestorage docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/keyvaluestorage/Dockerfile
      tags: openbp/obp-native-keyvaluestorage:latest,openbp/obp-native-keyvaluestorage:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-native-iam:
    needs: [tests,setup]
    name: Publish native_iam docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/native/services/iam/Dockerfile
      tags: openbp/obp-native-iam:latest,openbp/obp-native-iam:${{ needs.setup.outputs.tag }}
    secrets: inherit

  # Tools
  publish-tools-rest:
    needs: [tests,setup]
    name: Publish tools_rest docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/tools/services/rest/Dockerfile
      tags: openbp/obp-tools-rest:latest,openbp/obp-tools-rest:${{ needs.setup.outputs.tag }}
    secrets: inherit
  publish-tools-gui:
    needs: [tests,setup]
    name: Publish tools_gui docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/tools/services/gui/Dockerfile
      tags: openbp/obp-tools-gui:latest,openbp/obp-tools-gui:${{ needs.setup.outputs.tag }}
    secrets: inherit

  # CRM
  publish-crm-core:
    needs: [tests,setup]
    name: Publish crm_core docker image
    uses: ./.github/workflows/publish-service.yml
    with:
      dockerfile: modules/crm/services/core/Dockerfile
      tags: openbp/obp-crm-core:latest,openbp/obp-crm-core:${{ needs.setup.outputs.tag }}
    secrets: inherit

  github-release:
    needs:
      - publish-system-vault
      - publish-native-namespace
      - publish-native-keyvaluestorage
      - publish-native-iam
      - publish-native-actor-user
      - publish-tools-rest
      - publish-tools-gui
      - publish-crm-core
    name: Create github release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}