name: Run all tests
on:
  push:
    branches:
      - '**' #ignore tags, because tags will be tested using workflow_call during the release workflow
    paths-ignore:
      - "site/**"
      - "scripts/**"
  workflow_call:

jobs:
  test-native:
    name: "Test native module using developers docker-compose files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f modules/system/docker-compose.yml -f modules/native/docker-compose.yml build --parallel
      - name: Run the stack
        run: docker-compose -f docker-compose.yml -f modules/system/docker-compose.yml -f modules/native/docker-compose.yml up -d
      - name: Run tests
        run: docker run --network openbp_internal -v $PWD:/app node:alpine3.15 sh -c "cd /app/modules/testing && yarn && npx jest -i"
