name: Run all tests
on:
  push:
    branches:
      - '**' #ignore tags, because tags will be tested using workflow_call during the release workflow
    paths-ignore:
      - "site/**"
      - "scripts/**"
  workflow_call:

jobs:
  test-native:
    name: "Test native module using developers docker-compose files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prebuild one of the containers
        run: docker-compose -f docker-compose.yml -f modules/system/docker-compose.yml -f modules/native/docker-compose.yml build native_iam
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f modules/system/docker-compose.yml -f modules/native/docker-compose.yml build --parallel
      - name: Run the stack
        run: docker-compose -f docker-compose.yml -f modules/system/docker-compose.yml -f modules/native/docker-compose.yml up -d
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
      - name: Install test reporting tool
        run: go install gotest.tools/gotestsum@latest
      - name: Run smoke tests
        run: env $(cat ./modules/.test.env) gotestsum --format github-actions --junitfile TestResults-smoke.xml ./modules/native/testing/smoke/...
      - name: Run unit (whitebox) tests
        run: env $(cat ./modules/.test.env) gotestsum --format github-actions --junitfile TestResults-unit.xml ./modules/native/testing/unit/...
      - name: Run integration tests
        run: env $(cat ./modules/.test.env) gotestsum --format github-actions --junitfile TestResults-integration.xml ./modules/native/testing/integration/... ./modules/system/testing/integration/...
      - name: Upload test summary
        uses: test-summary/action@v2
        with:
          paths: "TestResults-*.xml"
        if: always()
